version = "0.2"
ignorePaths = [
  ".pre-commit-config.yaml",
  "pyproject.toml",
  "zensical.toml",
  ".gitignore",
]
words = [
  "zensical",
  "pyproject",
  "Justfile",
  "strikethrough",
  "Blockquotes",
  "println",
  "infty",
  "arithmatex",
]
