[project]
name = "personal-site"
version = "0.1.0"
description = "Personal site built with MkDocs"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
  "zensical>=0.0.15",
]

[tool.uv]
package = false
